{"name": "test_login_failed_by_wrong_datas[data1]", "status": "passed", "attachments": [{"name": "log", "source": "531883b4-59a0-4c20-b01b-287fe96b2fd3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'pthon111', 'check': '帐号或密码错误!'}"}], "start": 1561300556139, "stop": 1561300556841, "uuid": "c21a9627-a0c2-416e-9b8a-0e90959f26d7", "historyId": "6e0be4de4f617071e1391416ca412f0d", "fullName": "test_cases.test_login.TestLogin#test_login_failed_by_wrong_datas[data1]", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PCOS-2014PXGVWP"}, {"name": "thread", "value": "5284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}