{"name": "test_login_failed_by_wrong_datas[data1]", "status": "passed", "attachments": [{"name": "log", "source": "d1f7fbd2-6a86-4bca-9725-3e003172c58d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'pthon111', 'check': '帐号或密码错误!'}"}], "start": 1561304459219, "stop": 1561304460403, "uuid": "e953144a-eebc-4e4f-9426-fab8e3eb631d", "historyId": "6e0be4de4f617071e1391416ca412f0d", "fullName": "test_cases.test_login.TestLogin#test_login_failed_by_wrong_datas[data1]", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PCOS-2014PXGVWP"}, {"name": "thread", "value": "11440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}